"""removed extra gamification columns

Revision ID: 0e3f76c187ed
Revises: 2cef70a2b231
Create Date: 2026-07-18 11:39:57.564887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3f76c187ed'
down_revision = '2cef70a2b231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('signed_in',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('xp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('events_participated')
        batch_op.drop_column('exp')
        batch_op.drop_column('events_won')
        batch_op.drop_column('level')
        batch_op.drop_column('certificates_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificates_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('events_won', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('exp', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('events_participated', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('xp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('signed_in',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
