"""added submit_url

Revision ID: 2859e7313d2e
Revises: 6d9bd2c7fbb6
Create Date: 2026-07-17 18:17:02.776871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2859e7313d2e'
down_revision = '6d9bd2c7fbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('submission_url')

    # ### end Alembic commands ###
