"""xp points

Revision ID: 2cef70a2b231
Revises: 2859e7313d2e
Create Date: 2026-07-18 11:18:47.810049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cef70a2b231'
down_revision = '2859e7313d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signed_in', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('xp')
        batch_op.drop_column('signed_in')

    # ### end Alembic commands ###
