"""add achievements to users table

Revision ID: 40f16271a0dd
Revises: 3f1873b23ba7
Create Date: 2026-07-19 13:18:12.038638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f16271a0dd'
down_revision = '3f1873b23ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievements', sa.JSON(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('achievements')

    # ### end Alembic commands ###
