"""with time zone

Revision ID: 4f3d43aa6553
Revises: 32a185680964
Create Date: 2026-07-18 14:10:15.204296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3d43aa6553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_signed_in', 
                      type_=sa.DateTime(timezone=True),
                      postgresql_using="to_timestamp(last_signed_in)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_signed_in',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
