"""initialize database framework and add events table

Revision ID: fddc7627cec1
Revises: 
Create Date: 2026-07-12 11:08:31.312449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddc7627cec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('hosted_by', sa.String(length=100), nullable=True),
    sa.Column('registration_start', sa.DateTime(), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(), nullable=False),
    sa.Column('event_start_date', sa.DateTime(), nullable=True),
    sa.Column('submission_start', sa.DateTime(), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(), nullable=True),
    sa.Column('registration_url', sa.String(length=500), nullable=True),
    sa.Column('submit_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
